### ISSUE TITLE
Find a way to format sonification videos

### ISSUE THREAD

**Issue by reedeth** [scholarslab/clockwork#20]
Because right now I think they're totally unformatted and don't scale at all.

**Comment by jeremyboggs** [comment]
@reedeth Do you mean make them responsive, to different screen sizes? Or something else, like different video codecs?

**Comment by reedeth** [comment]
i mean so that they fit onto a mobile phone, responsive size-wise. Rachel
and I were having trouble in SuperCollider because it looks like she can
only make the videos so small. Any ideas?

**Comment by jeremyboggs** [comment]
This should be fixed in 1b8e6b88ec.
