### ISSUE TITLE
Update documentation page to match style

### ISSUE THREAD

**Issue by gilletgr** [scholarslab/clockwork#26]
Does it make the site look less clean/professional/cohesive? Is it a problem if the answer to that question is yes? If it is a problem, which page should we change?

**Comment by cacology** [comment]
I'm thinking about this too and I wonder if we might break-out multiple versions. The Bikeshed code is easy enough to adapt to the rest of the site (i.e., it's basically markdown) and we could simply provide a link to the differently formatted version

**Comment by cacology** [comment]
Will convert to the format of the rest of the site and link to the bikeshed version.
