### ISSUE TITLE
Hard to read clock over written text in curriculum (and likely elsewhere?)

### ISSUE THREAD

**Issue by gilletgr** [scholarslab/clockwork#28]
Might want to think about making the background and/or the font darker/a different color

**Comment by reedeth** [comment]
Agreed with this, was thinking the same thing

**Comment by bremend** [comment]
Yes. Was wondering if it might be possible to color the time clock bar at the bottom so it is visible on every page; or even better, to make the top of the time clock bar serve as the bottom threshold of the page so that it never has text showing up behind it?

**Comment by reedeth** [comment]
Closed with b1eb6479e8959dcffd6184165d880c9e1c90e5e5
