### ISSUE TITLE
Table of content for curriculum

### ISSUE THREAD

**Issue by gilletgr** [scholarslab/clockwork#32]
Should we leave the table of content w/o the hyperlinks or should it just be the drop-down accordion thing?

**Comment by reedeth** [comment]
I was going to issue this as well - I'm thinking we should make it where the introduction comes first NOT inside the accordion, then the table of contents below that, then the accordion-ed stuff. But I have some style things for the accordion I'll put in another issue

**Comment by bremend** [comment]
Agreed. I made a note yesterday when going through the site to the same effect: What if we put the introduction text where the TOC is currently--e.g. make the introduction its own separate section at the top of the Curriculum page, such that it is always expanded, and serves as an orienting narrative for users who click on the curriculum tab. The rest of the drop down menu stays the same and serves as the outline/TOC.
