### ISSUE TITLE
I'm thinking we may remove the "what constitutes data section" 

### ISSUE THREAD

**Issue by gilletgr** [scholarslab/clockwork#34]
and just incorporate into the data selection tab. Thoughts?

**Comment by reedeth** [comment]
I'm not finding this tab - do you mean the "What Constitutes Information" tab? But regardless, it's a really small drop down thing and probably should just be a part of the "How Did We Select Our Data" tab.

**Comment by bremend** [comment]
Yes. Agreed. Working on this as I copy edit the entire Curriculum page.

**Comment by gilletgr** [comment]
I got rid of the tab in the accordion and will incorporate B's text as I have it! :-D
