### ISSUE TITLE
Hyperlinks hard to see - new style for them?

### ISSUE THREAD

**Issue by reedeth** [scholarslab/clockwork#37]
I noticed this on the About page most, but it's probably applicable to others as well. When there was a link that I had already clicked, I could barely tell that it was there.

I remember a while back we considered styling hyperlinks so that they were more set apart from the text in which they were embedded (easier to see - like giving them an orange box or whatever), to emphasize the fact that a lot of what you need to know on the site is elsewhere. Maybe we should reconsider this?

**Comment by gilletgr** [comment]
Yes... they are impossible to see on the curriculum/learning page... I don't know how to change this, but I'm happy to go through and make the changes

**Comment by erochest** [comment]
Will be addressed by #65
