### ISSUE TITLE
Text and explanations on sonification page

### ISSUE THREAD

**Issue by reedeth** [scholarslab/clockwork#38]
First, the final text on the sonification page seems out of place - we also need to consider rewriting this. 

Second, I'm thinking we might want to have really concrete, thorough descriptions of exactly what's going on in these sonificaitons in the curriculum page, and link to them here.

**Comment by bremend** [comment]
Agreed re:  need to explain what the curriculum and documentation pages are doing vis-a-vis sonifications at the bottom of the Sonifications page. Also, working on concrete, thorough descriptions of sonifications for the curriculum page. 

Also: 
1. On the Sonifications page, we may be able to make the explanation of what the sonifications are and why they are there a bit more clear (e.g. make the connection between sonifications and the rest of what the site is doing more explicit). 
2. On the Sonifications page, the word "federal" doesn't need to be capitalized

**Comment by cacology** [comment]
Written, to be re-read in issue #66
