### ISSUE TITLE
Format inside accordion tabs on Curriculum for cellphones

### ISSUE THREAD

**Issue by reedeth** [scholarslab/clockwork#44]
When I read the inside of the accordion tabs on the Curriculum page on my phone, there is a lot of blank space on the left and right. This makes it so that the text is pretty narrow. I think this is because the accordion indents in a certain way. 

Is there any way we could make a media query of some kind to make sure that the full width of the device in question is being used?

**Comment by erochest** [comment]
Related to #20.

**Comment by jeremyboggs** [comment]
Fixed in bd9cd3136af8bf637a987cb5ccfeec62e79f4a0e.
