### ISSUE TITLE
Getting rid of outline lines on the accordion

### ISSUE THREAD

**Issue by reedeth** [scholarslab/clockwork#46]
Is there any way we can get rid of the outline boxes on the accordion? I haven't had a chance to mess around with its styling stuff yet, but I feel like those lines are kind of distracting.

**Comment by gilletgr** [comment]
I don't know, but I'd be happy to take a look tomorrow after our meeting/ coerce jeremy into helping us see if that's an option :D

**Comment by erochest** [comment]
Will be addressed in #65
