### ISSUE TITLE
The first sonification doesn't respond to changes in salary

### ISSUE THREAD

**Issue by cacology** [scholarslab/clockwork#50]
Since the first sonification is adjusted to a particular scale at the end, the salary used to calculate the hours worked doesn't change anything. Perhaps this doesn't matter? It's something for the workshopees to discover?

**Comment by racheldevorah** [comment]
I don't understand!

**Comment by cacology** [comment]
Maybe this doesn't matter, but the way that we're calculating the "yoyoyo" sonification, the hourly salary has no effect on the pitches. After applying it to get the hourly cost of various things, we then turn that into note data between 36 and... 82 or whatever it was. So, any variation between say someone with a high salary and someone with a low one, is lost. Maybe we don't care? Maybe we do?

On one hand, there are a few places for improvement in the synths, etc., which seem actually like useful things to leave in the pedagogical exercise. When we teach this, a student might notice, and then we could be like "great! fix it! think about sound" and---honestly---if they notice, then they've learned.

On the other hand, we do claim that our posted sonifications have something to do with salaries, which--as of now--I don't think they do. We could rephrase or something...

**Comment by cacology** [comment]
It might require reimagining how "yoyoyo" works to fix this, which might not be a good use of time. Perhaps we should just think carefully of how we explain? I'll assign myself to this to, since I'm happy to help.

**Comment by cacology** [comment]
Apparently you can have only one person assigned... so... okay

**Comment by cacology** [comment]
Will be resolved by #67
