### ISSUE TITLE
Curriculum, consistent voice?

### ISSUE THREAD

**Issue by cacology** [scholarslab/clockwork#51]
The curriculum section has a range of expressive modes, from something a bit like notes, to comments, to attributing thoughts to particular people. I don't think it works the way it is, but I see two possible approaches:

1.) Situate the document as a sort of bricolage, assemblage, antiquarian, thing and explain the tentative nature of some of the comments and the more-fleshed-out nature of others. (why, anyhow? make up a reason ;- )

2.) Rewrite the document for a consistent voice

**Comment by gilletgr** [comment]
Bremen is in the process of editing

**Comment by bremend** [comment]
Yep. On it.

**Comment by erochest** [comment]
Duplicate of #48
