### ISSUE TITLE
Tutorial reference card location?

### ISSUE THREAD

**Issue by cacology** [scholarslab/clockwork#53]
Where should it be? Right now, it's just on the back-end: https://github.com/scholarslab/clockwork/tree/gh-pages/reference-card

**Comment by racheldevorah** [comment]
yes! does it warrant its own accordion fold in the curriculum?

**Comment by cacology** [comment]
Makes sense to me- perhaps see what the Curriculum folks say? I'm not 100% about the mode and genre of that document, so if it would fit.

**Comment by erochest** [comment]
Duplicate of #35
