### ISSUE TITLE
Typos on sonification page

### ISSUE THREAD

**Issue by cacology** [scholarslab/clockwork#56]
Was part of issue #29, but I thought it deserved its own issue.

**Comment by racheldevorah** [comment]
fixed what I could! take another look!

**Comment by cacology** [comment]
Let's get @lydiawarren and @gilletgr in here, since this isn't my issue, I just split it off from the typos in Documentation issue, which IS my issue. ;- )

**Comment by gilletgr** [comment]
I don't see the typos...
