### ISSUE TITLE
Accessibility assessment

### ISSUE THREAD

**Issue by cacology** [scholarslab/clockwork#58]
We might consider doing one: https://www.w3.org/WAI/eval/template.html

Can screen-readers get to everything? I know we're particularly concerned with those who are vision impaired because of the results of our methodology.

**Comment by gilletgr** [comment]
This sounds groovy to me.

**Comment by erochest** [comment]
Will be addressed in #65, but I'll keep it open in the meantime.

**Comment by cacology** [comment]
This is much longer and more complicated than I expected, so I'm doing a simple computer-assisted check using two tools: FireBug and FireEyes (which uses aXe). Viz. https://getfirebug.com and http://getfirebug.com/wiki/index.php/Firebug_Extensions#FireEyes . I'm going to do put the problems in one issue and suggest a more detailed assessment in another issue.
